[2025-01-14 14:20:18,530][test_mtl_wrong.py][line:41][INFO] ---------------args---------------
Namespace(data_path='./data/Pymatgen_Wrapped/0/', batch_size=256, model_path='/data/ylh/MyExps/MOFV2/checkpoints/Hope_MTL_Extend/Hope_mtl_extend_epoch_119.pth', device='2', mode='test', top_k=5, parallel_model=False, test_name='Test_MTL_Wrong', num_workers=20, balanced=0, log_name='log/test/test_Test_MTL_Wrong_2025_01_14_14:20:14.log')
[2025-01-14 14:20:18,531][test_mtl_wrong.py][line:42][INFO] ---------------device---------------
cuda:2
[2025-01-14 14:20:18,531][test_mtl_wrong.py][line:43][INFO] ---------------lossfn---------------
CrossEntropyLoss()
